const productos = [
  { id: 1, nombre: "Laptop", categoria: "electronica", precio: 1200 },
  { id: 2, nombre: "Camiseta", categoria: "ropa", precio: 25 },
  { id: 3, nombre: "Smartphone", categoria: "electronica", precio: 800 },
  { id: 4, nombre: "Pantalón", categoria: "ropa", precio: 50 },
  { id: 5, nombre: "Auriculares", categoria: "electronica", precio: 150 },
  { id: 6, nombre: "Zapatos Deportivos", categoria: "calzado", precio: 90 },
  { id: 7, nombre: "Televisor", categoria: "electronica", precio: 600 },
  { id: 8, nombre: "Chaqueta", categoria: "ropa", precio: 80 },
  { id: 9, nombre: "Teclado", categoria: "electronica", precio: 70 },
  { id: 10, nombre: "Ratón", categoria: "electronica", precio: 30 },
  { id: 11, nombre: "Vestido", categoria: "ropa", precio: 45 },
  { id: 12, nombre: "Sandalias", categoria: "calzado", precio: 35 },
  { id: 13, nombre: "Monitor", categoria: "electronica", precio: 200 },
  { id: 14, nombre: "Gorra", categoria: "ropa", precio: 15 },
  { id: 15, nombre: "Cinturón", categoria: "ropa", precio: 20 },
  { id: 16, nombre: "Tablet", categoria: "electronica", precio: 400 },
  { id: 17, nombre: "Zapatillas de Casa", categoria: "calzado", precio: 25 },
  { id: 18, nombre: "Bufanda", categoria: "ropa", precio: 18 },
  {
    id: 19,
    nombre: "Cámara Fotográfica",
    categoria: "electronica",
    precio: 950,
  },
  { id: 20, nombre: "Corbata", categoria: "ropa", precio: 22 },
  { id: 21, nombre: "Impresora", categoria: "electronica", precio: 180 },
  { id: 22, nombre: "Botas", categoria: "calzado", precio: 120 },
  { id: 23, nombre: "Calcetines", categoria: "ropa", precio: 10 },
  { id: 24, nombre: "Reproductor MP3", categoria: "electronica", precio: 60 },
  { id: 25, nombre: "Blusa", categoria: "ropa", precio: 40 },
  { id: 26, nombre: "Zapatos Formales", categoria: "calzado", precio: 110 },
  { id: 27, nombre: "Plancha", categoria: "electrodomestico", precio: 70 },
  { id: 28, nombre: "Microondas", categoria: "electrodomestico", precio: 150 },
  { id: 29, nombre: "Heladera", categoria: "electrodomestico", precio: 900 },
  { id: 30, nombre: "Cartera", categoria: "accesorios", precio: 65 },
]

module.exports = productos
